'use client';
import { useEffect,useState } from 'react';
import { request } from '../lib/backend';
export default function AccountGate({onReady}:{onReady:()=>void}){
 const [setup,setSetup]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [connected,setConnected]=useState(false);
 async function check(){setError('');try{const r=await request('/api/auth/status');setSetup(r.needsSetup);setConnected(true);}catch(e){setConnected(false);setError((e as Error).message);}}
 useEffect(()=>{void check();},[]);
 return <div className="account-screen"><div className="panel account-card"><div className="brand-mark">D<span>↗</span></div><h1>Dragon Lord</h1><a href='/download' className='button secondary'>Download for Windows</a><p className="muted">{setup?'Create your café owner account.':'Sign in to your café workspace.'}</p><span className="badge confirmed">Live PostgreSQL backend</span>{error&&<div className="error-banner">{error}</div>}{connected?<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await request(setup?'/api/auth/setup':'/api/auth/login',{name:f.get('name')||'',email:f.get('email'),password:f.get('password')});onReady();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{setup&&<label className="field">Your name<input name="name" required autoComplete="name"/></label>}<label className="field">Email<input name="email" type="email" required autoComplete="username"/></label><label className="field">Password<input name="password" type="password" required minLength={setup?12:1} maxLength={200} autoComplete={setup?'new-password':'current-password'}/></label>{setup&&<p className="fine-print">Use a new password of at least 12 characters. This creates the owner account and 14 empty stations. No sample customer or payment records are imported.</p>}<button className="button primary full" disabled={busy}>{busy?'Connecting…':setup?'Create owner account':'Sign in'}</button></form>:<button className="button secondary full" onClick={check}>Retry backend connection</button>}<p className="fine-print">Device agents and payment connections are configured separately. No simulated payments or device controls are enabled in live mode.</p></div></div>;
}
