'use client';
import { useEffect, useState } from 'react';
import { ShieldCheck, Zap, ClipboardList, Plus, Check, RefreshCw, ExternalLink, AlertTriangle, HeartHandshake } from 'lucide-react';
import { money, type State, type Role } from '../lib/cafe';
import {request,remoteAction} from '../lib/backend';
type Note = { id:string; body:string; priority:string; resolved:boolean; at:number };
type Incident = { id:string; title:string; station:string; minutes:number; status:string; at:number };
export default function Operations({page,state,role,notify,live=false}:{page:string;state:State;role:Role;notify:(s:string)=>void;live?:boolean}) {
 const [notes,setNotes]=useState<Note[]>([]);const [incidents,setIncidents]=useState<Incident[]>([]);const [loaded,setLoaded]=useState(false);const [health,setHealth]=useState('Not checked');const [integrations,setIntegrations]=useState<any>(null);
 useEffect(()=>{if(live){void reload();setLoaded(true);return;}try{setNotes(JSON.parse(localStorage.getItem('dragon-handover')||'[]'));setIncidents(JSON.parse(localStorage.getItem('dragon-incidents')||'[]'));}catch{}setLoaded(true);},[]);
 useEffect(()=>{if(loaded&&!live){localStorage.setItem('dragon-handover',JSON.stringify(notes));localStorage.setItem('dragon-incidents',JSON.stringify(incidents));}},[notes,incidents,loaded]);
 async function reload(){try{const [ns,ins]=await Promise.all([request('/api/handover'),request('/api/incidents')]);setNotes(ns.map((n:any)=>({...n,at:new Date(n.created_at).getTime()})));setIncidents(ins.map((i:any)=>({...i,station:i.station_id,minutes:i.minutes_lost,at:new Date(i.created_at).getTime()})));}catch(e){notify((e as Error).message);}}
 async function save(action:string,data:any){try{await remoteAction(action,data);await reload();notify('Saved to PostgreSQL');}catch(e){notify((e as Error).message);}}
 async function check(){setHealth('Checking…');try{const j=await request('/api/integrations');setIntegrations(j);setHealth('Backend connected');}catch{setHealth('Backend unavailable — start the ASP.NET service');}}
 return <>
 {page==='Shift handover'&&<div className="settings-grid"><section className="panel settings-panel"><h2>Leave the next shift a clear picture.</h2><p className="muted">Record unfinished work, player requests, and equipment issues. {live ? "Notes are saved to the café database." : "Notes are stored on this device in demo mode."}</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(live){void save('handover',{body:String(f.get('body')),priority:String(f.get('priority'))});e.currentTarget.reset();return;}setNotes([{id:crypto.randomUUID(),body:String(f.get('body')),priority:String(f.get('priority')),resolved:false,at:Date.now()},...notes]);e.currentTarget.reset();notify('Handover note added');}}><label className="field">Handover note<input name="body" required maxLength={500} placeholder="e.g. PC-06 keyboard replacement arrives tomorrow"/></label><label className="field">Priority<select name="priority"><option>Normal</option><option>Urgent</option></select></label><button className="button primary"><Plus size={16}/>Add note</button></form></section><section className="panel settings-panel"><h2>Shift board <span className="badge">{notes.filter(n=>!n.resolved).length} open</span></h2>{notes.length===0&&<div className="empty"><ClipboardList size={30}/><p>No handover notes yet. Leave one for the next shift.</p></div>}{notes.map(n=><div className="audit-line" key={n.id}><span className={`badge ${n.priority==='Urgent'?'maintenance':''}`}>{n.resolved?'Resolved':n.priority}</span><p style={{margin:'10px 0'}}>{n.body}</p><small>{new Date(n.at).toLocaleString()}</small>{!n.resolved&&<button className="text-button" style={{marginTop:12}} onClick={()=>live?void save('resolveNote',{id:n.id}):setNotes(notes.map(x=>x.id===n.id?{...x,resolved:true}:x))}><Check size={14}/>Mark resolved</button>}</div>)}</section></div>}
 {page==='Service recovery'&&<><div className="info-strip"><HeartHandshake size={19}/>Track lost play time before issuing a credit. Only a manager or owner can approve compensation.</div><div className="settings-grid"><section className="panel settings-panel"><h2>Log an interruption</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(live){void save('incident',{title:String(f.get('title')),station:String(f.get('station')),minutes:Number(f.get('minutes'))});e.currentTarget.reset();return;}setIncidents([{id:crypto.randomUUID(),title:String(f.get('title')),station:String(f.get('station')),minutes:Number(f.get('minutes')),status:'Open',at:Date.now()},...incidents]);e.currentTarget.reset();notify('Interruption recorded for review');}}><label className="field">What happened?<input name="title" required placeholder="Game crash, power interruption, hardware issue…"/></label><div className="form-row"><label className="field">Station<select name="station">{state.stations.map(s=><option key={s.id}>{s.id}</option>)}</select></label><label className="field">Minutes lost<input name="minutes" type="number" required min="1" max="600" defaultValue="5"/></label></div><button className="button primary"><Plus size={16}/>Log interruption</button></form></section><section className="panel settings-panel"><h2>Recovery desk</h2>{!incidents.length&&<div className="empty"><ShieldCheck size={32}/><p>No interruptions reported.</p></div>}{incidents.map(i=><div className="audit-line" key={i.id}><strong>{i.station} · {i.title}</strong><small>{i.minutes} minutes lost · Suggested credit {money(Math.ceil(state.rates[state.stations.find(t=>t.id===i.station)!.zone]*i.minutes/60))}</small><div style={{display:'flex',gap:15,marginTop:12}}><span className="badge">{i.status}</span>{i.status==='Open'&&<button className="text-button" onClick={()=>{if(role==='Cashier'){notify('A manager must review compensation.');return;}if(live){void save('incidentReview',{id:i.id});return;}setIncidents(incidents.map(x=>x.id===i.id?{...x,status:'Reviewed'}:x));notify('Marked reviewed. Issue an audited credit from the customer profile; no funds moved here.');}}>Mark reviewed</button>}</div></div>)}</section></div></>}
 {page==='Automations'&&<><div className="info-strip"><Zap size={19}/>n8n handles follow-up work. Billing and session authority stay in the café backend.</div><div className="settings-grid"><section className="panel settings-panel"><h2>Automation centre</h2><p className="muted">The backend stores events before delivery and retries failures. Each event has a stable ID for deduplication.</p>{[{title:'Payment captured',body:'Record verified Razorpay credits and emit a payment event.'},{title:'Session completed',body:'Prepare end-of-session reporting and a receipt event.'},{title:'Shift handover',body:'Keep unresolved work visible to the next team.'},{title:'Service recovery',body:'Review interrupted sessions and trace compensation.'}].map(x=><div className="audit-line" key={x.title}><strong><Zap size={14}/> {x.title}</strong><small>{x.body}</small><span className="badge" style={{marginTop:10}}>Configuration required</span></div>)}</section><section className="panel settings-panel"><h2>Connections</h2><div className="integration-line"><ShieldCheck size={18}/>Razorpay · {integrations?.razorpay||'Awaiting account keys'}</div><div className="integration-line"><Zap size={18}/>n8n · {integrations?.n8n||'Local setup in progress'}</div><div className="integration-line"><AlertTriangle size={18}/>{health}</div><div className="action-grid"><button className="button secondary" onClick={check}><RefreshCw size={15}/>Check backend</button><a className="button secondary" href="http://127.0.0.1:5678" target="_blank" rel="noreferrer"><ExternalLink size={15}/>Open n8n</a></div><p className="fine-print">Local n8n is accessible only on this computer. External notifications require a configured workflow and destination credentials.</p></section></div></>}
 </>;
}
