export type Role = 'Owner' | 'Manager' | 'Cashier';
export type Status = 'Available' | 'Occupied' | 'Reserved' | 'Offline' | 'Maintenance';
export type Station = { id: string; zone: 'Standard' | 'VIP' | 'Console'; status: Status; game: string; online: boolean; };
export type Customer = { id: string; name: string; email: string; balance: number; member: boolean; };
export type Session = { id: string; stationId: string; customerId: string; started: number; ends: number; minutes: number; rate: number; reserved: number; ended?: number; charge?: number; pausedAt?: number; pausedMs: number; };
export type Entry = { id: string; key: string; customerId: string; kind: 'Payment' | 'Session' | 'Purchase' | 'Refund' | 'Compensation'; amount: number; at: number; note: string; };
export type Booking = { id: string; customerId: string; stations: string[]; start: number; end: number; status: 'Confirmed' | 'Cancelled' | 'No-show'; deposit: number; };
export type Product = { id: string; name: string; category: string; price: number; stock: number; emoji: string; };
export type Order = { id: string; stationId: string; customerId: string; items: { productId: string; qty: number }[]; total: number; status: 'Pending' | 'Preparing' | 'Delivered' | 'Cancelled'; at: number; };
export type State = { stations: Station[]; customers: Customer[]; sessions: Session[]; ledger: Entry[]; bookings: Booking[]; products: Product[]; orders: Order[]; audit: { at: number; actor: string; action: string }[]; waitlist: { id: string; name: string; size: number }[]; brand: { name: string; domain: string; logo: string }; rates: { Standard: number; VIP: number; Console: number }; warning: number; online: boolean; };
export const money = (n: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: n % 100 ? 2 : 0 }).format(n / 100);
export const uid = () => crypto.randomUUID();
export function seed(now = Date.now()): State {
  const customers = ['Arjun Mehta', 'Rohan Sharma', 'Sneha Patel', 'Kabir Singh', 'Ishaan Verma', 'Ananya Rao', 'Dev Malhotra', 'Guest 001'].map((name, i) => ({ id: `c${i}`, name, email: i === 7 ? '' : name.toLowerCase().replace(' ', '.') + '@example.com', balance: [125000, 85000, 92000, 60000, 145000, 78000, 46000, 30000][i], member: i !== 7 }));
  const occupied = [0, 1, 3, 4, 7, 8, 10, 12];
  const stations: Station[] = Array.from({ length: 14 }, (_, i) => ({ id: i < 12 ? `PC-${String(i + 1).padStart(2, '0')}` : `PS5-${i - 11}`, zone: i < 8 ? 'Standard' : i < 12 ? 'VIP' : 'Console', status: occupied.includes(i) ? 'Occupied' : i === 5 ? 'Maintenance' : i === 9 ? 'Reserved' : i === 11 ? 'Offline' : 'Available', game: i < 12 ? 'Valorant, Counter-Strike 2, Fortnite, Dota 2' : 'EA Sports FC, Gran Turismo 7', online: i !== 11 }));
  const sessions = occupied.map((i, j) => ({ id: `s${j}`, stationId: stations[i].id, customerId: customers[j].id, started: now - (20 + j * 4) * 60000, ends: now + [72, 8, 44, 96, 28, 112, 56, 38][j] * 60000, minutes: 150, rate: i < 8 ? 10000 : i < 12 ? 15000 : 20000, reserved: i < 8 ? 25000 : i < 12 ? 37500 : 50000, pausedMs: 0 }));
  return { stations, customers, sessions, ledger: [{ id: 'e0', key: 'seed', customerId: 'c0', kind: 'Payment', amount: 100000, at: now - 3600000, note: 'Cash · morning shift' }, { id: 'e1', key: 'seed2', customerId: 'c1', kind: 'Session', amount: -20000, at: now - 4000000, note: 'PC-03 · completed session' }], bookings: [{ id: 'b0', customerId: 'c4', stations: ['PC-10'], start: now + 7200000, end: now + 14400000, status: 'Confirmed', deposit: 0 }, { id: 'b1', customerId: 'c2', stations: ['PC-03', 'PC-04'], start: now + 18000000, end: now + 25200000, status: 'Confirmed', deposit: 0 }], products: [{ id: 'p0', name: 'Red Bull', category: 'Energy drinks', price: 15000, stock: 24, emoji: '⚡' }, { id: 'p1', name: 'Iced coffee', category: 'Beverages', price: 12000, stock: 18, emoji: '☕' }, { id: 'p2', name: 'Classic fries', category: 'Snacks', price: 10000, stock: 12, emoji: '🍟' }, { id: 'p3', name: 'Margherita pizza', category: 'Food', price: 22000, stock: 8, emoji: '🍕' }, { id: 'p4', name: 'Mineral water', category: 'Beverages', price: 3000, stock: 40, emoji: '💧' }, { id: 'p5', name: 'Nachos & dip', category: 'Snacks', price: 14000, stock: 3, emoji: '🌮' }], orders: [{ id: 'o0', stationId: 'PC-02', customerId: 'c1', items: [{ productId: 'p0', qty: 2 }], total: 30000, status: 'Pending', at: now - 180000 }, { id: 'o1', stationId: 'PC-09', customerId: 'c5', items: [{ productId: 'p2', qty: 1 }, { productId: 'p1', qty: 1 }], total: 22000, status: 'Preparing', at: now - 480000 }, { id: 'o2', stationId: 'PS5-1', customerId: 'c7', items: [{ productId: 'p4', qty: 2 }], total: 6000, status: 'Pending', at: now - 60000 }], audit: [{ at: now - 300000, actor: 'Manager', action: 'PC-06 marked for maintenance · keyboard replacement' }], waitlist: [{ id: 'w0', name: 'Aditya & friends', size: 3 }], brand: { name: 'Dragon Lord', domain: 'dragonlord.gg', logo: '' }, rates: { Standard: 10000, VIP: 15000, Console: 20000 }, warning: 10, online: true };
}
export function remaining(s: Session, now = Date.now()) { return Math.max(0, Math.ceil((s.ends - (s.pausedAt || now)) / 60000)); }
export function charge(s: Session, now = Date.now()) { const elapsed = Math.max(0, (s.pausedAt || now) - s.started - s.pausedMs); return Math.min(s.reserved, Math.ceil(Math.ceil(elapsed / 60000) * s.rate / 60)); }
export function availableBalance(s: State, customerId: string) { return (s.customers.find(c => c.id === customerId)?.balance || 0) - s.sessions.filter(x => !x.ended && x.customerId === customerId).reduce((a, x) => a + x.reserved, 0); }
export function authorize(role: Role, action: string) { if (role === 'Cashier' && ['settings', 'refund', 'stock', 'compensation', 'maintenance'].includes(action)) throw Error('A manager or owner is required for this action.'); if (action === 'settings' && role !== 'Owner') throw Error('Only the owner can change café settings.'); }
export function transact(state: State, action: string, data: any, role: Role, now = Date.now()): State {
  authorize(role, action); const s = structuredClone(state); const customer = s.customers.find(c => c.id === data.customerId);
  const entry = (kind: Entry['kind'], amount: number, key: string, note: string) => { if (s.ledger.some(e => e.key === key)) return false; if (!customer) throw Error('Select a customer.'); if (!Number.isSafeInteger(amount)) throw Error('Invalid monetary amount.'); customer.balance += amount; s.ledger.unshift({ id: uid(), key, kind, amount, customerId: customer.id, at: now, note }); return true; };
  if (action === 'customer') { if (!data.name?.trim()) throw Error('Enter a customer name.'); s.customers.push({ id: uid(), name: data.name.trim(), email: data.email || '', balance: 0, member: data.member }); }
  if (action === 'payment') { if (!(data.amount > 0) || !data.key) throw Error('Enter a positive payment amount.'); entry('Payment', data.amount, data.key, 'Cash · demo payment'); }
  if (action === 'start') {
    if (!s.online) throw Error('New sessions require online authorization. Existing prepaid sessions can continue.');
    const station = s.stations.find(x => x.id === data.stationId)!;
    if (!station || !station.online || !['Available', 'Reserved'].includes(station.status)) throw Error('This station is not available.');
    if (!customer || !Number.isInteger(data.minutes) || data.minutes < 1 || data.minutes > 600) throw Error('Select a customer and 1–600 minutes.');
    const ends = now + data.minutes * 60000; const rate = s.rates[station.zone]; const reserved = Math.ceil(rate * data.minutes / 60);
    if (s.bookings.some(b => b.status === 'Confirmed' && b.stations.includes(station.id) && now < b.end && ends > b.start)) throw Error('This session overlaps a reservation.');
    if (availableBalance(s, customer.id) < reserved) throw Error('Insufficient available balance. Record a payment first.');
    s.sessions.push({ id: uid(), stationId: station.id, customerId: customer.id, started: now, ends, minutes: data.minutes, rate, reserved, pausedMs: 0 }); station.status = 'Occupied';
  }
  if (['end', 'extend', 'transfer', 'pause', 'resume'].includes(action)) {
    const session = s.sessions.find(x => x.id === data.sessionId); if (session?.ended && action === 'end') return s; if (!session || session.ended) throw Error('This session has already ended.');
    if (action === 'end') { const total = charge(session, now); session.ended = now; session.charge = total; s.stations.find(x => x.id === session.stationId)!.status = 'Available'; const c = s.customers.find(x => x.id === session.customerId)!; c.balance -= total; s.ledger.unshift({ id: uid(), key: `end:${session.id}`, customerId: c.id, kind: 'Session', amount: -total, at: now, note: `${session.stationId} · receipt ${session.id.slice(0, 8).toUpperCase()}` }); }
    if (action === 'pause') { if (session.pausedAt) throw Error('Already paused.'); session.pausedAt = now; }
    if (action === 'resume') { if (!session.pausedAt) throw Error('Session is not paused.'); const gap = now - session.pausedAt; const newEnd = session.ends + gap; if (s.bookings.some(b => b.status === 'Confirmed' && b.stations.includes(session.stationId) && now < b.end && newEnd > b.start)) throw Error('Resuming would overlap a reservation. End or transfer the session.'); session.ends = newEnd; session.pausedMs += gap; delete session.pausedAt; }
    if (action === 'extend') { if (!s.online) throw Error('Extensions require controller authorization while online.'); const extra = Math.ceil(session.rate * data.minutes / 60); if (!(data.minutes > 0) || availableBalance(s, session.customerId) < extra) throw Error('Insufficient balance for extension.'); const newEnd = session.ends + data.minutes * 60000; if (s.bookings.some(b => b.status === 'Confirmed' && b.stations.includes(session.stationId) && now < b.end && newEnd > b.start)) throw Error('Extension overlaps a reservation.'); session.ends = newEnd; session.reserved += extra; session.minutes += data.minutes; }
    if (action === 'transfer') { const target = s.stations.find(x => x.id === data.stationId); if (!target || !target.online || target.status !== 'Available') throw Error('Choose an available, connected station.'); if (s.bookings.some(b => b.status === 'Confirmed' && b.stations.includes(target.id) && now < b.end && session.ends > b.start)) throw Error('Target station has a conflicting reservation.'); s.stations.find(x => x.id === session.stationId)!.status = 'Available'; target.status = 'Occupied'; session.stationId = target.id; }
  }
  if (action === 'maintenance') { const station = s.stations.find(x => x.id === data.stationId)!; if (station.status === 'Occupied') throw Error('End or transfer the session first.'); station.status = station.status === 'Maintenance' ? 'Available' : 'Maintenance'; }
  if (action === 'booking') { if (!customer || !data.stations.length || data.start < now || data.end <= data.start) throw Error('Choose a customer, seats, and a future time range.'); if (data.stations.some((id: string) => !s.stations.some(t => t.id === id && t.online && t.status !== 'Maintenance'))) throw Error('One or more seats are unavailable.'); if (s.bookings.some(b => b.status === 'Confirmed' && b.stations.some(id => data.stations.includes(id)) && data.start < b.end && data.end > b.start) || s.sessions.some(x => !x.ended && data.stations.includes(x.stationId) && data.start < x.ends && data.end > now)) throw Error('Those seats overlap an existing booking or session.'); if (!s.online) throw Error('Bookings need venue acknowledgement. Reconnect before confirming.'); s.bookings.push({ id: uid(), customerId: customer.id, stations: data.stations, start: data.start, end: data.end, status: 'Confirmed', deposit: 0 }); }
  if (action === 'cancelBooking') { s.bookings.find(b => b.id === data.id)!.status = data.noShow ? 'No-show' : 'Cancelled'; }
  if (action === 'order') { const p = s.products.find(x => x.id === data.productId)!; if (!p || p.stock < data.qty || !Number.isInteger(data.qty) || data.qty < 1) throw Error('Requested quantity is unavailable.'); const total = p.price * data.qty; if (!customer || availableBalance(s, customer.id) < total) throw Error('Insufficient available balance.'); p.stock -= data.qty; const id = uid(); entry('Purchase', -total, `order:${id}`, p.name); s.orders.unshift({ id, stationId: data.stationId, customerId: customer.id, items: [{ productId: p.id, qty: data.qty }], total, status: 'Pending', at: now }); }
  if (action === 'orderStatus') { const order = s.orders.find(o => o.id === data.id)!; if (['Delivered', 'Cancelled'].includes(order.status)) throw Error('This order is already closed.'); if (data.status === 'Cancelled') { order.items.forEach(i => s.products.find(p => p.id === i.productId)!.stock += i.qty); s.customers.find(c => c.id === order.customerId)!.balance += order.total; s.ledger.unshift({ id: uid(), key: `cancel:${order.id}`, customerId: order.customerId, kind: 'Refund', amount: order.total, at: now, note: `Cancelled order ${order.id.slice(0, 8)}` }); } order.status = data.status; }
  if (action === 'refund' || action === 'compensation') { if (!data.reason?.trim() || !(data.amount > 0)) throw Error('Enter a positive amount and a reason.'); if (action === 'refund' && availableBalance(s, data.customerId) < data.amount) throw Error('Refund exceeds available balance.'); entry(action === 'refund' ? 'Refund' : 'Compensation', action === 'refund' ? -data.amount : data.amount, data.key, data.reason); }
  if (action === 'stock') { const p = s.products.find(x => x.id === data.id)!; if (!Number.isInteger(data.qty) || p.stock + data.qty < 0 || !data.reason) throw Error('Enter a valid adjustment and reason.'); p.stock += data.qty; }
  if (action === 'settings') { s.brand = data.brand; s.rates = data.rates; s.warning = data.warning; }
  if (action === 'network') s.online = !s.online;
  if (action === 'waitlist') { if (!data.name || data.size < 1) throw Error('Enter a name and group size.'); s.waitlist.push({ id: uid(), name: data.name, size: data.size }); }
  if (action === 'removeWaitlist') s.waitlist = s.waitlist.filter(x => x.id !== data.id);
  s.audit.unshift({ at: now, actor: role, action: `${action} · ${data.reason || data.stationId || data.name || data.id || 'completed'}` }); return s;
}
